# Generated by Django 5.1.5 on 2025-04-02 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeslotTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslot_assignments', to='api.teacher')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslot_assignments', to='api.timeslot')),
            ],
        ),
    ]
