# Generated by Django 5.1.5 on 2025-02-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_level_storage_certificate_coursesession_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='quantiry',
            new_name='quantity',
        ),
    ]
