# Generated by Django 5.1.5 on 2025-02-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_quantiry_storage_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='checked_date',
        ),
    ]
