# Generated by Django 5.1.5 on 2025-02-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_attendance_checked_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checked_date',
            field=models.DateTimeField(null=True),
        ),
    ]
