# Generated by Django 5.1.5 on 2025-02-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_attendance_checked_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
