# Generated by Django 5.1.5 on 2025-03-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_attendance_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesession',
            name='session_number',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='storage',
            name='storage_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
