# Generated by Django 5.1.5 on 2025-03-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_attendance_end_time_attendance_start_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Level',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='level',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='levelName',
            new_name='typeName',
        ),
    ]
