# Generated by Django 5.1.5 on 2025-03-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_level_type_rename_level_course_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=3500),
        ),
    ]
